apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shiny
  labels:
    app: shiny
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shiny
    spec:
      containers:
      - name: app
        image: gcr.io/$GCLOUD_PROJECT/shiny
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
        - name: grpc-server
          containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: shiny
  labels:
    app: shiny
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
    name: http
  - port: 50051
    targetPort: grpc-server
    name: grpc
  selector:
    app: shiny
